version: '3.8'

services:
  react-app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules  # node_modules는 컨테이너 내부 사용
    environment:
      - CHOKIDAR_USEPOLLING=true  # Docker 환경에서 파일 변경 감지 개선
      - WATCHPACK_POLLING=true     # 추가 파일 감지 개선
    stdin_open: true
    tty: true 